export const COURSES = [
  {
    title: "Advanced Vector Field Systems",
    slug: "advanced-vector-field-systems",
    short_description: "Master 3D vector mathematics for electromagnetic field analysis and engineering applications.",
    description: "A rigorous exploration of vector field mathematics applied to real electromagnetic systems. Covers gradient, divergence, curl, and their physical interpretations in energy and signal systems.",
    learning_outcomes: "Apply vector calculus to EM field problems. Analyze field distributions in complex geometries. Model energy transfer using field mathematics.",
    price: 197,
    category: "electromagnetic_theory",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Vector Calculus Foundations", description: "Gradient, divergence, curl operators and physical meaning.", is_free_preview: true, duration_mins: 42 },
      { number: 2, title: "Field Equations Framework", description: "Maxwell's equations in vector form, field line analysis.", is_free_preview: false, duration_mins: 58 },
      { number: 3, title: "Boundary Conditions", description: "Tangential and normal field conditions at material interfaces.", is_free_preview: false, duration_mins: 51 },
      { number: 4, title: "Energy Density Distributions", description: "Electric and magnetic energy storage in field configurations.", is_free_preview: false, duration_mins: 47 },
      { number: 5, title: "Computational Field Analysis", description: "Numerical methods for complex field geometries.", is_free_preview: false, duration_mins: 63 },
      { number: 6, title: "System Integration", description: "Applying vector field analysis to real engineering prototypes.", is_free_preview: false, duration_mins: 55 },
    ]
  },
  {
    title: "Longitudinal Wave Mechanics",
    slug: "longitudinal-wave-mechanics",
    short_description: "Deep-dive into longitudinal wave propagation, compression dynamics, and resonance engineering.",
    description: "Comprehensive study of longitudinal wave behavior from acoustics to plasma physics. Covers propagation models, resonance, and experimental verification methods.",
    learning_outcomes: "Model longitudinal wave propagation in various media. Design resonance systems. Measure and verify wave parameters experimentally.",
    price: 247,
    category: "physics_frameworks",
    module_count: 7,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Wave Equation Derivations", description: "First-principles derivation of longitudinal wave equations.", is_free_preview: true, duration_mins: 48 },
      { number: 2, title: "Compression & Rarefaction Dynamics", description: "Pressure wave modeling and material response.", is_free_preview: false, duration_mins: 52 },
      { number: 3, title: "Resonance Cavity Design", description: "Tuning resonant structures for maximum energy coupling.", is_free_preview: false, duration_mins: 61 },
      { number: 4, title: "Standing Wave Nodes", description: "Node/antinode mapping and practical use cases.", is_free_preview: false, duration_mins: 44 },
      { number: 5, title: "Plasma Wave Interactions", description: "Ion-acoustic waves and plasma oscillation modes.", is_free_preview: false, duration_mins: 57 },
      { number: 6, title: "Measurement Techniques", description: "Experimental setup for longitudinal wave characterization.", is_free_preview: false, duration_mins: 49 },
      { number: 7, title: "Advanced Applications", description: "Industrial and research applications of longitudinal phenomena.", is_free_preview: false, duration_mins: 66 },
    ]
  },
  {
    title: "Energy System Frameworks",
    slug: "energy-system-frameworks",
    short_description: "Engineering models for energy capture, conversion, storage, and distribution in advanced systems.",
    description: "Systematic approach to engineering energy systems from capture to utilization. Covers thermodynamic models, conversion efficiency, and storage architectures.",
    learning_outcomes: "Design complete energy system architectures. Calculate conversion efficiencies. Select appropriate storage technologies for given applications.",
    price: 297,
    category: "energy_systems",
    module_count: 8,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Energy System Taxonomy", description: "Classification of energy systems by source, conversion, and application.", is_free_preview: true, duration_mins: 38 },
      { number: 2, title: "Thermodynamic Efficiency Limits", description: "Carnot limits, entropy, and practical efficiency analysis.", is_free_preview: false, duration_mins: 55 },
      { number: 3, title: "Electromagnetic Energy Capture", description: "Inductive, capacitive, and resonant energy harvesting.", is_free_preview: false, duration_mins: 62 },
      { number: 4, title: "Power Electronics Fundamentals", description: "Switching converters, regulation, and isolation.", is_free_preview: false, duration_mins: 71 },
      { number: 5, title: "Storage Technologies", description: "Battery, supercapacitor, and mechanical storage analysis.", is_free_preview: false, duration_mins: 59 },
      { number: 6, title: "Grid Integration", description: "Load matching, distribution, and grid-tie considerations.", is_free_preview: false, duration_mins: 48 },
      { number: 7, title: "Control System Design", description: "MPPT, BMS, and feedback control for energy systems.", is_free_preview: false, duration_mins: 67 },
      { number: 8, title: "Prototype Validation", description: "Test plans, measurement setup, and efficiency verification.", is_free_preview: false, duration_mins: 53 },
    ]
  },
  {
    title: "Electromagnetic Resonance Theory",
    slug: "electromagnetic-resonance-theory",
    short_description: "LC circuits, cavity resonators, and resonant coupling theory for advanced engineers.",
    description: "From LC tank circuits to microwave cavity resonators, this course covers resonance phenomena across frequency scales with engineering applications.",
    learning_outcomes: "Design resonant circuits and cavities. Analyze Q-factor and bandwidth. Apply resonance to wireless power and communications.",
    price: 197,
    category: "electromagnetic_theory",
    module_count: 5,
    level: "intermediate",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "RLC Circuit Analysis", description: "Series/parallel resonance, impedance matching, Q-factor.", is_free_preview: true, duration_mins: 45 },
      { number: 2, title: "Cavity Resonator Design", description: "TE/TM modes, resonant frequencies, quality factors.", is_free_preview: false, duration_mins: 60 },
      { number: 3, title: "Resonant Coupling Systems", description: "Mutual inductance, coupling coefficients, power transfer.", is_free_preview: false, duration_mins: 54 },
      { number: 4, title: "High-Q System Engineering", description: "Loss reduction, shielding, and Q enhancement techniques.", is_free_preview: false, duration_mins: 49 },
      { number: 5, title: "Application Systems", description: "Wireless charging, MRI coils, and antenna resonance.", is_free_preview: false, duration_mins: 58 },
    ]
  },
  {
    title: "Bioelectromagnetic Systems",
    slug: "bioelectromagnetic-systems",
    short_description: "Interface of electromagnetic fields with biological systems — theory, measurement, and devices.",
    description: "Covers the interaction of electromagnetic fields with biological tissue, EEG/EMG signal theory, biopotential amplifiers, and therapeutic device design.",
    learning_outcomes: "Understand field-tissue interaction. Design biopotential acquisition systems. Analyze EEG, EMG, and ECG signal chains.",
    price: 347,
    category: "bio_systems",
    module_count: 7,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Bioelectrical Signal Origins", description: "Resting potentials, action potentials, ionic mechanisms.", is_free_preview: true, duration_mins: 50 },
      { number: 2, title: "Electrode-Tissue Interface", description: "Contact impedance, half-cell potentials, noise models.", is_free_preview: false, duration_mins: 58 },
      { number: 3, title: "Instrumentation Amplifiers", description: "CMRR, input impedance, noise optimization for bio-signals.", is_free_preview: false, duration_mins: 65 },
      { number: 4, title: "EEG Signal Chain Design", description: "ADS1299 front-end, filtering, and artifact rejection.", is_free_preview: false, duration_mins: 72 },
      { number: 5, title: "EMG Acquisition Systems", description: "MyoWare integration, envelope detection, gesture classification.", is_free_preview: false, duration_mins: 61 },
      { number: 6, title: "Field Therapy Devices", description: "TENS, TMS principles, and regulatory considerations.", is_free_preview: false, duration_mins: 55 },
      { number: 7, title: "Clinical Data Standards", description: "HL7, FHIR, and bio-signal data pipelines.", is_free_preview: false, duration_mins: 48 },
    ]
  },
  {
    title: "Modulation Hierarchy Systems",
    slug: "modulation-hierarchy-systems",
    short_description: "Complete modulation taxonomy from AM/FM through digital modulation to advanced spread-spectrum techniques.",
    description: "Systematic study of signal modulation from analog fundamentals to advanced digital schemes. Covers theoretical analysis and SDR implementation.",
    learning_outcomes: "Implement AM, FM, PSK, QAM modulators. Analyze BER performance. Build SDR receivers with Python/GNU Radio.",
    price: 247,
    category: "signal_systems",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Analog Modulation Fundamentals", description: "AM, FM, PM — spectrum analysis and bandwidth.", is_free_preview: true, duration_mins: 44 },
      { number: 2, title: "Digital Modulation Schemes", description: "ASK, FSK, PSK, QAM — constellation diagrams.", is_free_preview: false, duration_mins: 62 },
      { number: 3, title: "Spread Spectrum Techniques", description: "DSSS, FHSS, CDMA — theory and implementation.", is_free_preview: false, duration_mins: 57 },
      { number: 4, title: "OFDM and Multicarrier", description: "Subcarrier design, cyclic prefix, synchronization.", is_free_preview: false, duration_mins: 68 },
      { number: 5, title: "SDR Implementation", description: "RTL-SDR, LimeSDR — receiver chain building.", is_free_preview: false, duration_mins: 75 },
      { number: 6, title: "Channel Coding Integration", description: "Error correction codes paired with modulation schemes.", is_free_preview: false, duration_mins: 52 },
    ]
  },
  {
    title: "Signal Processing Frameworks",
    slug: "signal-processing-frameworks",
    short_description: "DSP theory and practical implementations for engineers working with real-world signals.",
    description: "From Fourier transforms to adaptive filtering, this course builds a complete DSP toolkit for hardware engineers working with sensor and communication signals.",
    learning_outcomes: "Apply DFT/FFT to real signals. Design FIR/IIR filters. Implement adaptive algorithms for noise cancellation.",
    price: 197,
    category: "signal_systems",
    module_count: 6,
    level: "intermediate",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Fourier Analysis", description: "DFT, FFT, windowing functions, spectral leakage.", is_free_preview: true, duration_mins: 47 },
      { number: 2, title: "Digital Filter Design", description: "FIR/IIR design methodologies, bilinear transform.", is_free_preview: false, duration_mins: 63 },
      { number: 3, title: "Sampling Theory", description: "Nyquist, aliasing, anti-aliasing filter design.", is_free_preview: false, duration_mins: 41 },
      { number: 4, title: "Adaptive Filtering", description: "LMS, RLS algorithms for noise cancellation.", is_free_preview: false, duration_mins: 58 },
      { number: 5, title: "Real-Time DSP Implementation", description: "Fixed-point arithmetic, ARM CMSIS-DSP library.", is_free_preview: false, duration_mins: 69 },
      { number: 6, title: "Sensor Signal Conditioning", description: "ADC selection, anti-aliasing, and calibration.", is_free_preview: false, duration_mins: 54 },
    ]
  },
  {
    title: "High-Voltage Device Analysis",
    slug: "high-voltage-device-analysis",
    short_description: "Engineering analysis of high-voltage components, insulation, and corona effects in power systems.",
    description: "Systematic analysis of high-voltage phenomena for engineers designing power electronics, Tesla coils, and industrial equipment.",
    learning_outcomes: "Calculate dielectric breakdown voltages. Design HV insulation systems. Measure corona and partial discharge phenomena.",
    price: 297,
    category: "energy_systems",
    module_count: 7,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Dielectric Breakdown Theory", description: "Paschen curves, streamer theory, and avalanche mechanisms.", is_free_preview: true, duration_mins: 52 },
      { number: 2, title: "Insulation Materials", description: "Dielectric constants, loss tangent, and material selection.", is_free_preview: false, duration_mins: 48 },
      { number: 3, title: "Corona Discharge Analysis", description: "Onset voltage, ozone production, and mitigation.", is_free_preview: false, duration_mins: 61 },
      { number: 4, title: "HV Transformer Design", description: "Core selection, winding isolation, and HV insulation.", is_free_preview: false, duration_mins: 74 },
      { number: 5, title: "Switching Devices", description: "IGBTs, SCRs, and spark gaps in HV applications.", is_free_preview: false, duration_mins: 58 },
      { number: 6, title: "Protection Systems", description: "Overvoltage protection, grounding, and fault clearing.", is_free_preview: false, duration_mins: 43 },
      { number: 7, title: "Measurement & Safety", description: "HV probes, Faraday cages, and laboratory safety protocols.", is_free_preview: false, duration_mins: 66 },
    ]
  },
  {
    title: "Prototype Systems Engineering",
    slug: "prototype-systems-engineering",
    short_description: "Structured methodology for moving from concept to working prototype in advanced engineering systems.",
    description: "Complete prototype development lifecycle — from requirements through integration testing. Covers PCB design, firmware, and system validation.",
    learning_outcomes: "Define prototype requirements systematically. Execute PCB layout for complex analog/digital systems. Validate prototypes against specifications.",
    price: 347,
    category: "engineering_models",
    module_count: 8,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Requirements Engineering", description: "Functional and non-functional requirements, specifications.", is_free_preview: true, duration_mins: 39 },
      { number: 2, title: "System Architecture Design", description: "Block diagrams, partitioning analog/digital domains.", is_free_preview: false, duration_mins: 54 },
      { number: 3, title: "PCB Layout for Prototypes", description: "KiCad workflow, ground planes, decoupling strategy.", is_free_preview: false, duration_mins: 78 },
      { number: 4, title: "Firmware Architecture", description: "RTOS selection, task design, hardware abstraction layers.", is_free_preview: false, duration_mins: 65 },
      { number: 5, title: "Bring-Up Procedure", description: "Power sequencing, startup testing, failure analysis.", is_free_preview: false, duration_mins: 57 },
      { number: 6, title: "Integration Testing", description: "Module integration, regression testing, and bug tracking.", is_free_preview: false, duration_mins: 49 },
      { number: 7, title: "Performance Characterization", description: "Measurement plans, calibration, and specification verification.", is_free_preview: false, duration_mins: 61 },
      { number: 8, title: "Documentation Standards", description: "Technical documentation, BOM management, and handoff.", is_free_preview: false, duration_mins: 44 },
    ]
  },
  {
    title: "Plasma Physics Engineering",
    slug: "plasma-physics-engineering",
    short_description: "Applied plasma physics for engineers — arc discharge, glow discharge, and plasma device design.",
    description: "Bridge between theoretical plasma physics and engineering implementation. Covers plasma generation, control, and measurement techniques.",
    learning_outcomes: "Characterize plasma with Langmuir probes. Design RF plasma sources. Build glow discharge tubes and arc systems safely.",
    price: 397,
    category: "physics_frameworks",
    module_count: 7,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Plasma State of Matter", description: "Ionization, recombination, Debye shielding, plasma frequency.", is_free_preview: true, duration_mins: 55 },
      { number: 2, title: "DC Glow Discharge", description: "Paschen breakdown, cathode/anode regions, spectroscopy.", is_free_preview: false, duration_mins: 62 },
      { number: 3, title: "RF Plasma Sources", description: "Capacitive and inductive coupling, matching networks.", is_free_preview: false, duration_mins: 70 },
      { number: 4, title: "Magnetic Confinement", description: "Tokamak geometry basics, mirror fields, and cusps.", is_free_preview: false, duration_mins: 64 },
      { number: 5, title: "Langmuir Probe Diagnostics", description: "I-V curves, electron temperature, density measurements.", is_free_preview: false, duration_mins: 58 },
      { number: 6, title: "Plasma Devices", description: "Ion thrusters, plasma cutters, and lighting applications.", is_free_preview: false, duration_mins: 73 },
      { number: 7, title: "Safety & Radiation", description: "UV exposure, X-ray risk, and plasma lab safety.", is_free_preview: false, duration_mins: 47 },
    ]
  },
  {
    title: "Wireless Power Transfer Systems",
    slug: "wireless-power-transfer",
    short_description: "Resonant inductive coupling, WPT architectures, and efficiency optimization for wireless charging.",
    description: "Complete engineering guide to wireless power transfer from near-field inductive systems to mid-range resonant designs used in EV charging and medical implants.",
    learning_outcomes: "Design resonant WPT coils. Calculate coupling coefficients. Optimize efficiency vs. distance tradeoffs.",
    price: 247,
    category: "energy_systems",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Near-Field WPT Fundamentals", description: "Inductive coupling, mutual inductance, coil geometry.", is_free_preview: true, duration_mins: 46 },
      { number: 2, title: "Resonant WPT Design", description: "SS, SP, PS, PP topologies — analysis and tradeoffs.", is_free_preview: false, duration_mins: 63 },
      { number: 3, title: "Coil Design & Optimization", description: "Litz wire, ferrite shielding, spatial tolerance.", is_free_preview: false, duration_mins: 57 },
      { number: 4, title: "Power Electronics for WPT", description: "Inverter design, rectifier selection, regulation.", is_free_preview: false, duration_mins: 69 },
      { number: 5, title: "Efficiency Measurement", description: "S-parameter measurement, power analyzer setup.", is_free_preview: false, duration_mins: 51 },
      { number: 6, title: "Standards & Compliance", description: "Qi, AirFuel, SAE J2954 — standards analysis.", is_free_preview: false, duration_mins: 44 },
    ]
  },
  {
    title: "Antenna Theory & Design",
    slug: "antenna-theory-design",
    short_description: "Antenna fundamentals, design methodologies, and simulation tools for RF engineering.",
    description: "From dipoles to phased arrays, this course covers antenna parameters, design trade-offs, simulation in 4NEC2/HFSS, and practical measurement.",
    learning_outcomes: "Calculate gain, radiation pattern, and impedance. Design and simulate patch antennas. Measure antenna performance with VNA.",
    price: 197,
    category: "electromagnetic_theory",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Antenna Parameters", description: "Gain, directivity, efficiency, bandwidth, polarization.", is_free_preview: true, duration_mins: 43 },
      { number: 2, title: "Wire Antenna Analysis", description: "Dipoles, monopoles, Yagi-Uda — current distributions.", is_free_preview: false, duration_mins: 58 },
      { number: 3, title: "Aperture Antennas", description: "Horn, patch, and slot antenna design.", is_free_preview: false, duration_mins: 66 },
      { number: 4, title: "Phased Array Systems", description: "Array factor, beam steering, grating lobes.", is_free_preview: false, duration_mins: 72 },
      { number: 5, title: "Antenna Simulation", description: "4NEC2, HFSS workflow, S11 and pattern analysis.", is_free_preview: false, duration_mins: 55 },
      { number: 6, title: "VNA Measurement", description: "Calibration, S-parameter measurement, feed design.", is_free_preview: false, duration_mins: 49 },
    ]
  },
  {
    title: "Electromagnetic Compatibility Engineering",
    slug: "emc-engineering",
    short_description: "EMC design principles, shielding, grounding, and compliance testing for hardware engineers.",
    description: "Practical EMC engineering from PCB design through compliance testing. Covers conducted and radiated emissions, susceptibility, and pre-compliance testing.",
    learning_outcomes: "Design PCBs for EMC compliance. Implement effective shielding and filtering. Conduct pre-compliance testing with LISN and near-field probes.",
    price: 247,
    category: "electromagnetic_theory",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "EMC Fundamentals", description: "Radiated and conducted emissions/immunity, standards overview.", is_free_preview: true, duration_mins: 44 },
      { number: 2, title: "PCB Design for EMC", description: "Ground planes, layer stackup, decoupling, trace routing.", is_free_preview: false, duration_mins: 68 },
      { number: 3, title: "Filtering Techniques", description: "Common-mode chokes, ferrite beads, π-filters.", is_free_preview: false, duration_mins: 52 },
      { number: 4, title: "Shielding Design", description: "Enclosure shielding effectiveness, seams, apertures.", is_free_preview: false, duration_mins: 61 },
      { number: 5, title: "Pre-Compliance Testing", description: "LISN, near-field probes, spectrum analyzer techniques.", is_free_preview: false, duration_mins: 74 },
      { number: 6, title: "Compliance Standards", description: "FCC Part 15, CISPR 32, CE marking — test plans.", is_free_preview: false, duration_mins: 49 },
    ]
  },
  {
    title: "Power Supply Design Mastery",
    slug: "power-supply-design",
    short_description: "Complete power supply design from linear regulators through LLC resonant converters.",
    description: "Systematic power supply design methodology covering topology selection, magnetics design, loop compensation, and efficiency optimization.",
    learning_outcomes: "Select appropriate PSU topology for any application. Design magnetics from first principles. Compensate control loops for stability.",
    price: 297,
    category: "energy_systems",
    module_count: 8,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Topology Selection", description: "Buck, boost, flyback, forward — when to use each.", is_free_preview: true, duration_mins: 50 },
      { number: 2, title: "Inductor & Transformer Design", description: "Core material, air gap, winding calculations.", is_free_preview: false, duration_mins: 73 },
      { number: 3, title: "Switch Mode Converter Analysis", description: "CCM/DCM analysis, ripple, and loss calculations.", is_free_preview: false, duration_mins: 62 },
      { number: 4, title: "Control Loop Design", description: "Type II/III compensators, Bode plot analysis.", is_free_preview: false, duration_mins: 69 },
      { number: 5, title: "Resonant Topologies", description: "LLC, CLLC converter design and optimization.", is_free_preview: false, duration_mins: 78 },
      { number: 6, title: "PCB Layout for Power", description: "Current loops, thermal management, gate drive layout.", is_free_preview: false, duration_mins: 56 },
      { number: 7, title: "Efficiency Optimization", description: "Synchronous rectification, soft switching, GaN/SiC.", is_free_preview: false, duration_mins: 64 },
      { number: 8, title: "Testing & Validation", description: "Load transient, efficiency curves, thermal imaging.", is_free_preview: false, duration_mins: 47 },
    ]
  },
  {
    title: "Neural Interface Engineering",
    slug: "neural-interface-engineering",
    short_description: "Brain-computer interface engineering — signal acquisition, processing, and closed-loop systems.",
    description: "Advanced course covering neural signal acquisition hardware, spike sorting, neural decoding, and closed-loop stimulation systems.",
    learning_outcomes: "Design neural amplifier front-ends. Implement basic spike sorting algorithms. Build closed-loop stimulation systems.",
    price: 397,
    category: "bio_systems",
    module_count: 7,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Neural Signal Characteristics", description: "LFPs, spikes, ECoG — amplitude, frequency, and noise.", is_free_preview: true, duration_mins: 56 },
      { number: 2, title: "Recording Electrode Systems", description: "Utah array, tetrodes, μECoG — materials and impedance.", is_free_preview: false, duration_mins: 63 },
      { number: 3, title: "Analog Front-End Design", description: "Noise optimization, bandwidth selection, gain stages.", is_free_preview: false, duration_mins: 75 },
      { number: 4, title: "Spike Sorting Algorithms", description: "Threshold detection, PCA, template matching.", is_free_preview: false, duration_mins: 68 },
      { number: 5, title: "Neural Decoding", description: "Population vectors, Wiener filter, LSTM decoders.", is_free_preview: false, duration_mins: 71 },
      { number: 6, title: "Closed-Loop Stimulation", description: "Charge-balanced pulses, safety limits, feedback control.", is_free_preview: false, duration_mins: 64 },
      { number: 7, title: "Implantable System Design", description: "Packaging, biocompatibility, wireless telemetry.", is_free_preview: false, duration_mins: 59 },
    ]
  },
  {
    title: "RF System Design",
    slug: "rf-system-design",
    short_description: "End-to-end RF system design covering link budget, noise figure, and transceiver architectures.",
    description: "Complete RF system engineering from link budget analysis through transceiver design, covering superheterodyne and direct-conversion architectures.",
    learning_outcomes: "Calculate RF link budgets. Design LNA, mixer, and VCO circuits. Analyze noise figure and intermodulation distortion.",
    price: 297,
    category: "signal_systems",
    module_count: 7,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Link Budget Analysis", description: "Friis equation, path loss, link margin calculation.", is_free_preview: true, duration_mins: 48 },
      { number: 2, title: "Noise Figure Analysis", description: "Cascade noise figure, sensitivity calculation.", is_free_preview: false, duration_mins: 57 },
      { number: 3, title: "LNA Design", description: "S-parameter matching, noise optimization, stability.", is_free_preview: false, duration_mins: 69 },
      { number: 4, title: "Mixer Circuits", description: "Single/double-balanced mixers, conversion gain, isolation.", is_free_preview: false, duration_mins: 61 },
      { number: 5, title: "Oscillator & PLL Design", description: "VCO design, phase noise, PLL loop filter.", is_free_preview: false, duration_mins: 74 },
      { number: 6, title: "Transceiver Architectures", description: "Superheterodyne vs. direct-conversion tradeoffs.", is_free_preview: false, duration_mins: 52 },
      { number: 7, title: "RF PCB Design", description: "Controlled impedance, via stitching, component placement.", is_free_preview: false, duration_mins: 63 },
    ]
  },
  {
    title: "Control Systems Engineering",
    slug: "control-systems-engineering",
    short_description: "Classical and modern control theory applied to real engineering systems with practical design exercises.",
    description: "From PID controllers to state-space methods, this course builds a complete control theory toolkit with direct application to hardware systems.",
    learning_outcomes: "Design PID controllers using Ziegler-Nichols and loop-shaping. Analyze system stability using root locus and Nyquist criteria. Implement digital controllers.",
    price: 247,
    category: "engineering_models",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Transfer Function Analysis", description: "Laplace transforms, poles/zeros, stability.", is_free_preview: true, duration_mins: 49 },
      { number: 2, title: "PID Controller Design", description: "Tuning methods, windup protection, derivative filtering.", is_free_preview: false, duration_mins: 64 },
      { number: 3, title: "Frequency Domain Design", description: "Bode plots, gain/phase margins, loop shaping.", is_free_preview: false, duration_mins: 58 },
      { number: 4, title: "State Space Methods", description: "State feedback, pole placement, Kalman filter.", is_free_preview: false, duration_mins: 72 },
      { number: 5, title: "Digital Control Implementation", description: "Discretization, z-domain analysis, microcontroller implementation.", is_free_preview: false, duration_mins: 66 },
      { number: 6, title: "Nonlinear Control", description: "Sliding mode, Lyapunov methods, adaptive control.", is_free_preview: false, duration_mins: 53 },
    ]
  },
  {
    title: "Quantum-Classical Interface Systems",
    slug: "quantum-classical-interface",
    short_description: "Practical engineering at the boundary of quantum and classical systems — measurement, decoherence, and control.",
    description: "Engineering course bridging quantum mechanics and classical electronics, covering quantum measurement, qubit control electronics, and low-noise cryogenic design.",
    learning_outcomes: "Understand qubit control electronics requirements. Design low-noise amplifiers for quantum measurement. Analyze decoherence sources in quantum systems.",
    price: 397,
    category: "physics_frameworks",
    module_count: 6,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Quantum Systems Overview", description: "Qubits, superposition, entanglement — engineering perspective.", is_free_preview: true, duration_mins: 54 },
      { number: 2, title: "Qubit Control Electronics", description: "Microwave pulse generation, IQ mixing, waveform synthesis.", is_free_preview: false, duration_mins: 71 },
      { number: 3, title: "Cryogenic Electronic Design", description: "Low-noise amplification at 4K, heat load analysis.", is_free_preview: false, duration_mins: 67 },
      { number: 4, title: "Decoherence Analysis", description: "T1, T2 times, noise spectroscopy methods.", is_free_preview: false, duration_mins: 62 },
      { number: 5, title: "Quantum Measurement Circuits", description: "Dispersive readout, JPA amplifiers, signal chain.", is_free_preview: false, duration_mins: 75 },
      { number: 6, title: "Classical Control Stack", description: "FPGA-based real-time control for quantum feedback.", is_free_preview: false, duration_mins: 59 },
    ]
  },
  {
    title: "Advanced Sensor Systems",
    slug: "advanced-sensor-systems",
    short_description: "Sensor physics, signal conditioning, calibration, and fusion for precision measurement systems.",
    description: "Complete sensor engineering from physical transduction through data fusion. Covers MEMS, optical, and electrochemical sensors with signal conditioning design.",
    learning_outcomes: "Select sensors based on noise and dynamic range requirements. Design signal conditioning for precision measurement. Implement sensor fusion algorithms.",
    price: 197,
    category: "engineering_models",
    module_count: 5,
    level: "intermediate",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Sensor Taxonomy & Selection", description: "Transduction mechanisms, noise types, selection criteria.", is_free_preview: true, duration_mins: 43 },
      { number: 2, title: "Signal Conditioning Design", description: "Amplification, filtering, impedance matching for sensors.", is_free_preview: false, duration_mins: 60 },
      { number: 3, title: "MEMS Sensor Systems", description: "Accelerometers, gyroscopes, pressure sensors — integration.", is_free_preview: false, duration_mins: 55 },
      { number: 4, title: "Calibration Methods", description: "Two-point, polynomial, and temperature compensation.", is_free_preview: false, duration_mins: 48 },
      { number: 5, title: "Sensor Fusion", description: "Kalman filter, complementary filter for IMU fusion.", is_free_preview: false, duration_mins: 64 },
    ]
  },
  {
    title: "Electromagnetic Field Manipulation",
    slug: "em-field-manipulation",
    short_description: "Engineering techniques for shaping, focusing, and steering electromagnetic fields in practical systems.",
    description: "Advanced techniques for controlling EM field distributions — from metamaterial-based beam steering to phased arrays and near-field focusing.",
    learning_outcomes: "Design field-shaping structures. Simulate near-field distributions. Engineer metamaterial unit cells for field control.",
    price: 347,
    category: "electromagnetic_theory",
    module_count: 7,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Field Shaping Fundamentals", description: "Green's functions, image theory, near-field distributions.", is_free_preview: true, duration_mins: 51 },
      { number: 2, title: "Metamaterial Unit Cells", description: "SRR, wire medium — effective medium parameters.", is_free_preview: false, duration_mins: 68 },
      { number: 3, title: "Phased Array Beam Steering", description: "Phase shifter design, grating lobes, mutual coupling.", is_free_preview: false, duration_mins: 76 },
      { number: 4, title: "Near-Field Focusing", description: "Superlenses, focusing via evanescent waves.", is_free_preview: false, duration_mins: 63 },
      { number: 5, title: "Frequency Selective Surfaces", description: "FSS design, band-pass/stop behavior, angular stability.", is_free_preview: false, duration_mins: 57 },
      { number: 6, title: "Reconfigurable Structures", description: "PIN diode, varactor, and MEMS-tuned EM structures.", is_free_preview: false, duration_mins: 71 },
      { number: 7, title: "Full-Wave Simulation", description: "FDTD, FEM setup for complex EM geometries.", is_free_preview: false, duration_mins: 64 },
    ]
  },
  {
    title: "Embedded Systems Architecture",
    slug: "embedded-systems-architecture",
    short_description: "Hardware-software co-design for advanced embedded systems targeting research and engineering applications.",
    description: "Systems-level embedded design from SoC selection through real-time software architecture. Covers ARM Cortex-M, RTOS, and hardware abstraction.",
    learning_outcomes: "Architect embedded systems from scratch. Write production-quality HAL code. Profile and optimize real-time performance.",
    price: 247,
    category: "engineering_models",
    module_count: 7,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "SoC Architecture", description: "ARM Cortex-M core, bus matrix, peripheral map.", is_free_preview: true, duration_mins: 47 },
      { number: 2, title: "Hardware Abstraction Layer", description: "HAL design patterns, driver architecture.", is_free_preview: false, duration_mins: 62 },
      { number: 3, title: "RTOS Fundamentals", description: "FreeRTOS tasks, queues, semaphores, priority inversion.", is_free_preview: false, duration_mins: 71 },
      { number: 4, title: "DMA & Peripheral Config", description: "DMA transfers, SPI/I2C/UART at register level.", is_free_preview: false, duration_mins: 58 },
      { number: 5, title: "Power Management", description: "Sleep modes, RTC wakeup, low-power peripheral strategy.", is_free_preview: false, duration_mins: 54 },
      { number: 6, title: "Real-Time Analysis", description: "Profiling, stack analysis, worst-case execution time.", is_free_preview: false, duration_mins: 66 },
      { number: 7, title: "Bootloader & OTA", description: "Custom bootloader, secure boot, OTA update design.", is_free_preview: false, duration_mins: 53 },
    ]
  },
  {
    title: "Electrostatic Systems & Devices",
    slug: "electrostatic-systems",
    short_description: "Electrostatic field engineering, charge dynamics, and practical electrostatic device design.",
    description: "Comprehensive study of electrostatic phenomena from Coulomb's law through MEMS electrostatic actuators and high-voltage electrostatic generators.",
    learning_outcomes: "Calculate electrostatic fields in complex geometries. Design electrostatic actuators. Build Van de Graaff and Wimshurst machine variants.",
    price: 197,
    category: "physics_frameworks",
    module_count: 5,
    level: "intermediate",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Electrostatic Field Theory", description: "Coulomb's law, Gauss's law, potential theory.", is_free_preview: true, duration_mins: 45 },
      { number: 2, title: "Charge Storage Systems", description: "Capacitor design, dielectric selection, energy density.", is_free_preview: false, duration_mins: 57 },
      { number: 3, title: "Electrostatic Actuators", description: "MEMS comb drives, parallel plate actuators.", is_free_preview: false, duration_mins: 63 },
      { number: 4, title: "High-Voltage Generators", description: "Van de Graaff, Wimshurst, and Cockcroft-Walton circuits.", is_free_preview: false, duration_mins: 68 },
      { number: 5, title: "Electrostatic Shielding", description: "Faraday cage design, triboelectric effects, grounding.", is_free_preview: false, duration_mins: 51 },
    ]
  },
  {
    title: "Magnetohydrodynamics Applied",
    slug: "magnetohydrodynamics-applied",
    short_description: "MHD theory and engineering — plasma drives, liquid metal pumps, and magnetized plasma confinement.",
    description: "Applied magnetohydrodynamics for engineers, covering conducting fluid behavior in magnetic fields, MHD drives, and plasma confinement geometries.",
    learning_outcomes: "Analyze MHD channel flow. Design electromagnetic liquid metal pumps. Model Lorentz force in conducting fluid systems.",
    price: 347,
    category: "physics_frameworks",
    module_count: 6,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "MHD Governing Equations", description: "Navier-Stokes, induction equation, coupling parameters.", is_free_preview: true, duration_mins: 53 },
      { number: 2, title: "Hartmann Flow Analysis", description: "Hartmann number, velocity profiles, boundary layers.", is_free_preview: false, duration_mins: 61 },
      { number: 3, title: "Electromagnetic Pumps", description: "Linear induction pump design for liquid metals.", is_free_preview: false, duration_mins: 69 },
      { number: 4, title: "MHD Power Generation", description: "Faraday-type MHD generators, electrode design.", is_free_preview: false, duration_mins: 64 },
      { number: 5, title: "Plasma Confinement MHD", description: "Pinch instabilities, kink modes, stability criteria.", is_free_preview: false, duration_mins: 72 },
      { number: 6, title: "Numerical MHD Methods", description: "OpenFOAM MHD solver setup and validation.", is_free_preview: false, duration_mins: 57 },
    ]
  },
  {
    title: "Frequency Domain Engineering",
    slug: "frequency-domain-engineering",
    short_description: "Advanced frequency-domain analysis — impedance spectroscopy, network analysis, and S-parameter design.",
    description: "Deep dive into frequency-domain methods used in RF engineering, power electronics, and materials characterization.",
    learning_outcomes: "Measure complex impedance with VNA. Interpret S-parameters for circuit design. Apply network synthesis techniques.",
    price: 247,
    category: "signal_systems",
    module_count: 5,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Impedance Fundamentals", description: "Complex impedance, admittance, and circuit models.", is_free_preview: true, duration_mins: 42 },
      { number: 2, title: "VNA Theory & Calibration", description: "S-parameters, SOLT calibration, error correction.", is_free_preview: false, duration_mins: 65 },
      { number: 3, title: "Network Synthesis", description: "Ladder networks, Butterworth/Chebyshev design.", is_free_preview: false, duration_mins: 59 },
      { number: 4, title: "Impedance Spectroscopy", description: "EIS for batteries, corrosion, and dielectric analysis.", is_free_preview: false, duration_mins: 71 },
      { number: 5, title: "Signal Integrity Analysis", description: "TDR, eye diagrams, channel equalization.", is_free_preview: false, duration_mins: 54 },
    ]
  },
  {
    title: "Gravitational & Inertial Sensing",
    slug: "gravitational-inertial-sensing",
    short_description: "Precision inertial sensing — from MEMS accelerometers to cold-atom gravimeters and their engineering applications.",
    description: "Advanced inertial sensing systems from consumer MEMS through laboratory-grade gravimeters. Covers noise fundamentals, vibration isolation, and signal processing.",
    learning_outcomes: "Characterize MEMS inertial sensor performance. Design vibration isolation systems. Understand cold-atom gravity sensing architecture.",
    price: 297,
    category: "engineering_models",
    module_count: 6,
    level: "advanced",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Inertial Sensing Physics", description: "Spring-mass model, Brownian noise, resolution limits.", is_free_preview: true, duration_mins: 48 },
      { number: 2, title: "MEMS Accelerometers", description: "Capacitive sensing, fabrication, and performance tradeoffs.", is_free_preview: false, duration_mins: 61 },
      { number: 3, title: "Gyroscope Systems", description: "Coriolis effect, vibratory gyros, scale factor.", is_free_preview: false, duration_mins: 57 },
      { number: 4, title: "Vibration Isolation", description: "Passive/active isolation, seismic platforms, feedback.", is_free_preview: false, duration_mins: 64 },
      { number: 5, title: "Precision Gravimetry", description: "FG5, cold-atom gravimeters — principles and applications.", is_free_preview: false, duration_mins: 73 },
      { number: 6, title: "INS & Navigation", description: "Strapdown INS, error propagation, GNSS integration.", is_free_preview: false, duration_mins: 55 },
    ]
  },
  {
    title: "Advanced Physics Framework Integration",
    slug: "advanced-physics-framework",
    short_description: "Unified framework connecting electromagnetism, quantum mechanics, and thermodynamics for advanced engineering.",
    description: "Capstone course unifying classical and quantum frameworks for advanced engineering applications. Covers cross-domain modeling and emergent phenomena.",
    learning_outcomes: "Connect EM and quantum frameworks for engineering problems. Model thermodynamic constraints on electronic systems. Analyze emergent phenomena across scales.",
    price: 397,
    category: "physics_frameworks",
    module_count: 8,
    level: "expert",
    instructor: "Scalar Vault Research Team",
    modules: [
      { number: 1, title: "Classical-Quantum Boundary", description: "Correspondence principle, semiclassical methods.", is_free_preview: true, duration_mins: 55 },
      { number: 2, title: "Statistical Mechanics for Engineers", description: "Partition functions, Fermi-Dirac, Bose-Einstein.", is_free_preview: false, duration_mins: 67 },
      { number: 3, title: "Non-Equilibrium Thermodynamics", description: "Onsager relations, entropy production in open systems.", is_free_preview: false, duration_mins: 61 },
      { number: 4, title: "Electromagnetic-Thermal Coupling", description: "Joule heating, Peltier effect, thermoelectric systems.", is_free_preview: false, duration_mins: 59 },
      { number: 5, title: "Condensed Matter Basics", description: "Band theory, superconductivity, topological materials.", is_free_preview: false, duration_mins: 74 },
      { number: 6, title: "Scale-Bridging Methods", description: "Multiscale modeling from atomic to continuum.", is_free_preview: false, duration_mins: 66 },
      { number: 7, title: "Emergent Phenomena", description: "Self-organization, chaos, and complexity in engineering.", is_free_preview: false, duration_mins: 58 },
      { number: 8, title: "Unified Engineering Models", description: "Cross-domain design patterns and abstraction layers.", is_free_preview: false, duration_mins: 72 },
    ]
  },
];

export const CATEGORY_LABELS = {
  electromagnetic_theory: 'Electromagnetic Theory',
  energy_systems: 'Energy Systems',
  signal_systems: 'Signal Systems',
  bio_systems: 'Bio/Neural Systems',
  engineering_models: 'Engineering Models',
  physics_frameworks: 'Physics Frameworks',
};

export const CATEGORY_COLORS = {
  electromagnetic_theory: 'text-primary bg-primary/10 border-primary/25',
  energy_systems: 'text-chart-4 bg-chart-4/10 border-chart-4/25',
  signal_systems: 'text-chart-3 bg-chart-3/10 border-chart-3/25',
  bio_systems: 'text-chart-5 bg-chart-5/10 border-chart-5/25',
  engineering_models: 'text-accent bg-accent/10 border-accent/25',
  physics_frameworks: 'text-chart-2 bg-chart-2/10 border-chart-2/25',
};