// Product Ladder — Scalar Venture Vault
// SaaS Monetization Strategy: Free → Subscription → Digital Products → Kits → High-Ticket

export const PRODUCT_LADDER = {
  free: {
    id: 'free',
    tier: 0,
    name: 'Free Preview',
    price: 0,
    billing: null,
    tagline: 'Enough to create demand. Not enough to satisfy it.',
    conversion_goal: 'Email capture → Starter upgrade',
    includes: [
      'First section of every build (preview only)',
      'AI Engineering Assistant (3 queries/day)',
      'Build cost estimates visible',
      'Community forum access (read-only)',
      'Weekly new build announcement email',
    ],
    excludes: [
      'Full schematics & wiring diagrams',
      'Complete BOM with supplier links',
      'Step-by-step execution guide',
      'Code & firmware downloads',
      'Video walkthroughs',
    ],
    upsell_trigger: 'Paywall modal after reading preview section',
    upsell_message: "You're reading the preview. The build starts on the next page.",
    color: 'muted',
    icon: 'Eye',
  },

  starter: {
    id: 'starter',
    tier: 1,
    name: 'Starter',
    price: 49,
    billing: 'month',
    annual_price: 39,
    tagline: 'Access to the vault. Limits that encourage upgrading.',
    conversion_goal: 'Starter → Pro upgrade after 2nd build',
    includes: [
      'Access to 15 builds (rotating monthly)',
      'Full schematics & BOMs',
      'Step-by-step execution guides',
      'Code & firmware downloads',
      'AI Engineering Assistant (20 queries/day)',
      'Community forum (post + comment)',
      'New build every Friday (1-week delay)',
    ],
    excludes: [
      'Full vault access (47 builds)',
      'Early access to new builds (48hr)',
      'Starter kits (member discount)',
      'High-ticket mentorship sessions',
      'Priority support',
    ],
    upsell_trigger: 'Hit the 15-build limit or see a locked Pro-only build',
    upsell_message: "You've unlocked 15 builds. 32 more are waiting in Pro.",
    color: 'cyan',
    icon: 'Zap',
    highlight: false,
  },

  pro: {
    id: 'pro',
    tier: 2,
    name: 'Pro',
    price: 99,
    billing: 'month',
    annual_price: 79,
    tagline: 'Full vault. Full execution power.',
    conversion_goal: 'Pro → Elite upgrade after 6 months',
    includes: [
      'Full vault — all 47 builds, always',
      'Early access to new builds (48hr before free)',
      'Full schematics, BOMs, supplier links',
      'All code, firmware & CAD files',
      'AI Engineering Assistant (unlimited)',
      'Community forum (all access)',
      '20% discount on all starter kits',
      'Monthly build livestream (Pro members only)',
      'Priority support (24hr response)',
    ],
    excludes: [
      '1-on-1 mentorship sessions',
      'Custom build consultation',
      'Elite cohort access',
      'Revenue share program',
    ],
    upsell_trigger: 'Completing 3+ builds or interest in advanced project',
    upsell_message: 'Ready to go from builds to a product? Elite members get mentorship.',
    color: 'cyan',
    icon: 'Star',
    highlight: true,
    badge: 'Most Popular',
  },

  elite: {
    id: 'elite',
    tier: 3,
    name: 'Elite',
    price: 299,
    billing: 'month',
    annual_price: 249,
    tagline: 'From engineer to entrepreneur.',
    conversion_goal: 'Retain → upsell to Build-to-Launch program',
    includes: [
      'Everything in Pro',
      '2x monthly 1-on-1 mentorship sessions (60 min)',
      'Custom build consultation (your project)',
      'Elite cohort — private Slack with 50 engineers',
      'Revenue share program (sell your builds)',
      'Early access to high-ticket programs',
      'Featured in vault as community builder',
      'Free starter kit per quarter',
      '48hr custom circuit review turnaround',
    ],
    excludes: [],
    upsell_trigger: 'Organic — when Pro member has a commercial project',
    upsell_message: "If you're building something commercial, we want to help you launch it.",
    color: 'purple',
    icon: 'Crown',
    highlight: false,
    badge: 'Best Value',
  },
};

export const DIGITAL_PRODUCTS = [
  {
    id: 'dp_eeg',
    name: 'EEG Brain-Computer Interface — Complete Guide',
    category: 'bio_signal_systems',
    price: 497,
    what_you_get: [
      'Complete 80-page build guide (PDF)',
      'Full schematics (KiCad + PDF)',
      'Verified BOM with 3 supplier options per component',
      'Arduino + Python codebase (GitHub access)',
      'Signal processing Jupyter notebook',
      'Troubleshooting guide (30 documented failure points)',
      'Lifetime updates',
    ],
    ideal_for: 'Engineers who want this build only, without a subscription',
    upsell_to: 'Pro subscription (saves $398 vs buying 4 guides)',
    conversion_note: 'After purchase, offer Pro trial at $1 for first month',
  },
  {
    id: 'dp_tesla',
    name: 'Tesla Coil Power Transmitter — Complete Guide',
    category: 'energy_systems',
    price: 397,
    what_you_get: [
      'Complete 60-page build guide (PDF)',
      'Full schematics with component tolerances',
      'LC circuit calculation spreadsheet',
      'Safety enclosure design files',
      'Resonance tuning guide',
      'Lifetime updates',
    ],
    ideal_for: 'One-time purchasers, gift buyers, course creators',
    upsell_to: 'Starter kit bundle (+$180)',
    conversion_note: 'Kit upsell shown immediately post-purchase',
  },
  {
    id: 'dp_sdr',
    name: 'SDR Intelligence Station — Complete Guide',
    category: 'communication_systems',
    price: 297,
    what_you_get: [
      'Complete 50-page setup guide',
      'Antenna design calculations',
      'Software configuration walkthrough',
      'Frequency reference guide (100+ signal types)',
      'Satellite pass schedule integration',
      'Lifetime updates',
    ],
    ideal_for: 'Radio enthusiasts, security researchers, hobbyists',
    upsell_to: 'SDR Starter Kit (+$95)',
    conversion_note: 'Show as entry product — lowest price point for paid',
  },
  {
    id: 'dp_emg',
    name: 'EMG Gesture Controller — Complete Guide',
    category: 'bio_signal_systems',
    price: 397,
    what_you_get: [
      'Complete 65-page build guide',
      'PCB design files (Gerber + KiCad)',
      'ML gesture classification model (Python)',
      'MyoWare sensor integration guide',
      'Training data pipeline',
      'Lifetime updates',
    ],
    ideal_for: 'Robotics engineers, AR/VR developers, prosthetics researchers',
    upsell_to: 'EMG Starter Kit (+$210)',
    conversion_note: 'Highest-intent buyers — target for Elite upsell',
  },
];

export const STARTER_KITS = [
  {
    id: 'kit_eeg',
    name: 'EEG BCI Starter Kit',
    build: 'EEG Brain-Computer Interface',
    price: 249,
    member_price: 199,
    retail_value: 380,
    includes: [
      'ADS1299 analog front-end board (pre-assembled)',
      'Dry electrode set (8 channels)',
      'ESP32 development board',
      'PCB breakout board (pre-soldered)',
      'Conductive gel (30ml)',
      'Electrode headset mount (3D printed)',
      'USB-C power cable',
    ],
    ships_in: '3-5 business days',
    margin_note: '68% margin at member price',
    upsell_to: 'Digital guide bundle (+$97)',
  },
  {
    id: 'kit_tesla',
    name: 'Tesla Coil Starter Kit',
    build: 'Tesla Coil Power Transmitter',
    price: 189,
    member_price: 149,
    retail_value: 290,
    includes: [
      'Pre-wound primary coil (copper tubing)',
      'Secondary coil form (machined PVC)',
      '28AWG magnet wire (200m)',
      'IRFP260N MOSFETs (x4)',
      'Gate drive transformer (pre-wound)',
      'Toroid topload (aluminum, 4")',
      'Safety enclosure hardware',
    ],
    ships_in: '5-7 business days',
    margin_note: '72% margin at member price',
    upsell_to: 'Pro subscription for video walkthrough',
  },
  {
    id: 'kit_sdr',
    name: 'SDR Intelligence Starter Kit',
    build: 'SDR Intelligence Station',
    price: 95,
    member_price: 75,
    retail_value: 140,
    includes: [
      'RTL-SDR v3 dongle (R820T2 chip)',
      'Dipole antenna set (adjustable)',
      'SMA to MCX adapter',
      'Telescopic whip antenna (for VHF/UHF)',
      'USB extension cable (3m)',
    ],
    ships_in: '2-3 business days',
    margin_note: '61% margin at member price',
    upsell_to: 'Pro subscription for full frequency guide',
  },
  {
    id: 'kit_emg',
    name: 'EMG Gesture Controller Kit',
    build: 'EMG Gesture Controller',
    price: 229,
    member_price: 185,
    retail_value: 340,
    includes: [
      'MyoWare 2.0 muscle sensor (x2)',
      'Custom PCB (pre-assembled)',
      'Arduino Nano Every',
      'Electrode snap connectors (x20)',
      'Disposable electrodes (x50)',
      'Armband mount (adjustable)',
      'USB programming cable',
    ],
    ships_in: '3-5 business days',
    margin_note: '65% margin at member price',
    upsell_to: 'Elite tier for ML model customization session',
  },
];

export const HIGH_TICKET = [
  {
    id: 'ht_bootcamp',
    name: 'Build-to-Launch Bootcamp',
    price: 2997,
    format: '8-week live program',
    cohort_size: 12,
    tagline: 'Take one build from prototype to monetizable product in 8 weeks.',
    curriculum: [
      'Week 1-2: Select and build your core system (guided)',
      'Week 3: BOM optimization and cost reduction for scale',
      'Week 4: Market validation — who pays for this?',
      'Week 5: Productization — from prototype to sellable kit',
      'Week 6: Go-to-market strategy and pricing',
      'Week 7: Digital product creation from your build guide',
      'Week 8: Launch + first sale or client',
    ],
    includes: [
      '8 weekly live sessions (90 min each)',
      'Private cohort Slack channel',
      'Direct access to instructor for build reviews',
      'Pro subscription for bootcamp duration',
      'Lifetime vault access post-bootcamp',
      'Revenue split on any kit or guide you publish',
    ],
    ideal_for: 'Pro/Elite members with a project ready to monetize',
    conversion_from: 'Elite members, digital product buyers',
    ltv_note: 'Alumni become kit sellers — recurring revenue share',
  },
  {
    id: 'ht_consult',
    name: 'Custom Build Consultation',
    price: 497,
    format: '90-minute 1-on-1 session',
    tagline: 'Bring your hardest engineering problem. Leave with a build plan.',
    includes: [
      'Pre-session questionnaire and scope review',
      '90-minute live engineering session',
      'Component selection review',
      'Custom BOM delivered within 48hr',
      'Schematic review or design recommendations',
      'Follow-up async review (1 week post-session)',
    ],
    ideal_for: 'Engineers with a specific project outside the vault',
    conversion_from: 'Pro members, digital product buyers',
    upsell_to: 'Elite membership or Bootcamp',
  },
  {
    id: 'ht_license',
    name: 'White-Label Build License',
    price: 4997,
    format: 'One-time license per build',
    tagline: 'License any Scalar Vault build to use in your course, bootcamp, or product.',
    includes: [
      'Commercial license for 1 vault build',
      'Editable source files (KiCad, Markdown, CAD)',
      'Co-branding rights',
      'Direct support channel for your students',
      'Revenue share waiver for your first 100 units',
    ],
    ideal_for: 'Course creators, universities, corporate training programs',
    conversion_from: 'Organic inbound, Elite referrals',
    upsell_to: 'Multi-build license package ($14,997 for 5)',
  },
];

export const UPSELL_FLOWS = [
  {
    from: 'Free',
    to: 'Starter',
    trigger: 'Hits paywall after reading build preview',
    mechanism: 'Paywall modal — A/B tested headline, urgency bar, objection FAQ',
    offer: '$49/mo or $39/mo annual — first month at $1 for email subscribers',
    conversion_benchmark: '4-8% of preview readers',
  },
  {
    from: 'Starter',
    to: 'Pro',
    trigger: 'Attempts to access a Pro-only build OR hits 15-build limit',
    mechanism: 'In-app banner + email sequence at day 7 and day 14',
    offer: 'Upgrade for $50/mo more — unlock 32 more builds today',
    conversion_benchmark: '22% of Starter members within 60 days',
  },
  {
    from: 'Pro',
    to: 'Elite',
    trigger: 'Completes 3+ builds, asks a complex custom question in AI assistant',
    mechanism: 'Personalized email from founder + in-dashboard prompt',
    offer: 'Private invite — limited to 50 members',
    conversion_benchmark: '8% of Pro members after 3 months',
  },
  {
    from: 'Free / Starter',
    to: 'Digital Product',
    trigger: 'Tries to buy specific guide without subscribing',
    mechanism: 'Shown on build detail page — "Own it forever" vs "Access in Pro"',
    offer: 'One-time purchase, no subscription required',
    conversion_benchmark: '1.5-3% of build page visitors',
  },
  {
    from: 'Digital Product Buyer',
    to: 'Starter / Pro',
    trigger: 'Post-purchase email at day 1 and day 3',
    mechanism: '$1 first month offer — "You bought the guide, get the vault"',
    offer: 'Try Pro for $1 — cancel before month 2',
    conversion_benchmark: '31% of digital product buyers trial Pro',
  },
  {
    from: 'Kit Buyer',
    to: 'Subscription',
    trigger: 'Immediately post-kit purchase',
    mechanism: 'Order confirmation page — "Your kit ships in 3-5 days. Start the guide now."',
    offer: '$1 first month Pro — guide access before kit arrives',
    conversion_benchmark: '44% of kit buyers start a subscription',
  },
  {
    from: 'Pro / Elite',
    to: 'Bootcamp',
    trigger: 'Completes 5+ builds OR asks about monetizing a project',
    mechanism: 'Direct founder outreach + waitlist email sequence',
    offer: '$2,997 one-time — 8-week cohort, 12 seats max',
    conversion_benchmark: '3-5% of tenured Pro/Elite members per cohort',
  },
  {
    from: 'Starter Kit',
    to: 'Digital Guide Bundle',
    trigger: 'Kit order confirmation page',
    mechanism: 'Order bump — "Add the complete guide for $97 more"',
    offer: 'Kit + Complete Guide bundle — save $50 vs buying separately',
    conversion_benchmark: '27% order bump rate',
  },
];